import "./globals.css";

import Header from "../components/Header";
import { createServerComponentClient } from "@supabase/auth-helpers-nextjs";
import { cookies } from "next/headers";
import { redirect } from "next/navigation";
import type { Database } from "@/types/supabase";

export const metadata = {
  title: "Next.js",
  description: "Generated by Next.js",
};

export default async function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  const supabase = createServerComponentClient<Database>({ cookies });

  const {
    data: { session },
  } = await supabase.auth.getSession();

  return (
    <html lang="en" className="scroll-smooth text-xl md:text-base xl:text-sm">
      <body className="flex flex-col min-h-screen m-0 overflow-x-hidden">
        <div className="pt-16 bg-transparent border-none ">
          {/** must stay othervice header might overlap with other things */}
        </div>
        <Header user={session?.user!} />

        {children}
      </body>
    </html>
  );
}
