// import globals.css
import "./globals.css";

import Header from "../components/Header";

export const metadata = {
  title: "Next.js",
  description: "Generated by Next.js",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en" className="scroll-smooth">
      <body className="flex flex-col min-h-screen m-0 overflow-x-hidden">
        <Header />
        {children}
      </body>
    </html>
  );
}
