import "./globals.css";

import Header from "../components/Header";
import { createServerComponentClient } from "@supabase/auth-helpers-nextjs";
import { cookies } from "next/headers";
import { redirect } from "next/navigation";
import type { Database } from "@/types/supabase";

export const metadata = {
  title: "Next.js",
  description: "Generated by Next.js",
};

export const dynamic = "force-dynamic";

export default async function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  const supabase = createServerComponentClient<Database>({ cookies });

  const {
    data: { session },
  } = await supabase.auth.getSession();

  return (
    <html lang="en" className="scroll-smooth">
      <body className="flex flex-col min-h-screen m-0 overflow-x-hidden">
        <Header />
        <div className="flex-1 bg-main bg-fixed bg-cover flex  flex-col">
          {children}
        </div>
      </body>
    </html>
  );
}
